name: Azure Static Web Apps CI/CD
on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional: fail early if secret missing
      - name: Sanity check token presence (masked)
        run: '[ -z "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}" ] && echo "Token missing" && exit 1 || echo "Token present"'

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          production_branch: main
          app_location: "/"
          app_build_command: "npm install && npm run build"
          app_artifact_location: "build"
          output_location: "build"
